export const lineWidth = 1;
export const radiusColor = "rgba(255,0,0,0.5)";
export const lineColor = "rgba(233, 32, 79,0.3)";
export const circleColor = lineColor;
export const mouseColor ="rgba(0, 200, 30,0.3)";
export const allowedRadius = 80;
export const nodeSize = 5;
export const allowedDistance = 100;
export const mouseRadius = 150;
